## 4.1.6 further experiments

The following experiments will help convince you that the architecture choices you’ve made are all fairly reasonable, although there’s still room for improvement:

a)You used two representation layers before the final classification layer. Try using one or three representation layers, and see how doing so affects validation and test accuracy.

b)Try using layers with more units or fewer units: 32 units, 64 units, and so on. 


c)Try using the mse loss function instead of binary_crossentropy. 


d)Try using the tanh activation (an activation that was popular in the early days of neural networks) instead of relu.

## a) vou fazer com 3 camadas de representação

In [1]:
from keras.datasets import imdb
(train_data, train_labels), (test_data, test_labels) = imdb.load_data(num_words=10000)

preparar os dados via multihot-encoding.

In [5]:
import numpy as np
def vectorize_sequences(sequences, dimension=10000):
    results = np.zeros((len(sequences), dimension))
    for i, sequence in enumerate(sequences):
        for j in sequence:
            if j < dimension:
                results[i,j] = 1.
    return results

x_train = vectorize_sequences(train_data)
x_test = vectorize_sequences(test_data)

agora vectorizar as labels com o autoencoding

In [8]:
y_train = np.asarray(train_labels).astype("float32")
y_test = np.asarray(test_labels).astype("float32")

building the model

In [ ]:
from tensorflow import keras
from keras import layers

In [13]:
#modelo construido com 3 camadas de representação
model = keras.Sequential([
    layers.Dense(16, activation="relu"),
    layers.Dense(1, activation="sigmoid"),
])

model.compile(optimizer="rmsprop",
            loss="binary_crossentropy",
            metrics=["accuracy"])

history = model.fit(x_train, y_train, epochs=4, batch_size=512)
results = model.evaluate(x_test,y_test)

Epoch 1/4
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8204 - loss: 0.4581
Epoch 2/4
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9015 - loss: 0.2902
Epoch 3/4
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9194 - loss: 0.2353
Epoch 4/4
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9291 - loss: 0.2043
782/782 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8886 - loss: 0.2782


In [15]:
print(results)

[0.27823323011398315, 0.8885999917984009]


In [16]:
model.predict(x_test)

782/782 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step


array([[0.24820134],
       [0.99905443],
       [0.88097155],
       ...,
       [0.13657558],
       [0.12448619],
       [0.6021751 ]], shape=(25000, 1), dtype=float32)

conclusão, 1 camada de representação teve melhor rsultado que 3

b)Try using layers with more units or fewer units: 32 units, 64 units, and so on. 

In [34]:
#modelo construido com 3 camadas de representação
model = keras.Sequential([
    layers.Dense(16, activation="relu"),
    layers.Dense(1, activation="sigmoid"),
])

model.compile(optimizer="rmsprop",
            loss="binary_crossentropy",
            metrics=["accuracy"])

history = model.fit(x_train, y_train, epochs=4, batch_size=512)
results = model.evaluate(x_test,y_test)

Epoch 1/4
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8244 - loss: 0.4527
Epoch 2/4
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9020 - loss: 0.2833
Epoch 3/4
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9202 - loss: 0.2297
Epoch 4/4
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9302 - loss: 0.1998
782/782 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8860 - loss: 0.2821


In [36]:
print(results)

[0.2821428179740906, 0.8859599828720093]


In [37]:
model.predict(x_test)

782/782 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step


array([[0.21612944],
       [0.9994577 ],
       [0.7716147 ],
       ...,
       [0.094501  ],
       [0.07492308],
       [0.50994766]], shape=(25000, 1), dtype=float32)

## c)Try using the mse loss function instead of binary_crossentropy.

In [38]:
#modelo construido com 3 camadas de representação
model = keras.Sequential([
    layers.Dense(16, activation="relu"),
    layers.Dense(1, activation="sigmoid"),
])

model.compile(optimizer="rmsprop",
            loss="mse",
            metrics=["accuracy"])

history = model.fit(x_train, y_train, epochs=4, batch_size=512)
results = model.evaluate(x_test,y_test)

Epoch 1/4
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8120 - loss: 0.1561
Epoch 2/4
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8944 - loss: 0.0941
Epoch 3/4
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9107 - loss: 0.0768
Epoch 4/4
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9211 - loss: 0.0673
782/782 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8892 - loss: 0.0853


In [39]:
print(results)

[0.08529828488826752, 0.889240026473999]


In [40]:
model.predict(x_test)

782/782 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step  


array([[0.2829184 ],
       [0.997542  ],
       [0.78685075],
       ...,
       [0.1564425 ],
       [0.14355719],
       [0.4691588 ]], shape=(25000, 1), dtype=float32)

### d)Try using the tanh activation (an activation that was popular in the early days of neural networks) instead of relu.

In [42]:
#modelo construido com 3 camadas de representação
model = keras.Sequential([
    layers.Dense(16, activation="tanh"),
    layers.Dense(1, activation="sigmoid"),
])

model.compile(optimizer="rmsprop",
            loss="mse",
            metrics=["accuracy"])

history = model.fit(x_train, y_train, epochs=4, batch_size=512)
results = model.evaluate(x_test,y_test)

print(results)

model.predict(x_test)

Epoch 1/4
49/49 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8160 - loss: 0.1639
Epoch 2/4
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8884 - loss: 0.1031
Epoch 3/4
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9049 - loss: 0.0821
Epoch 4/4
49/49 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9174 - loss: 0.0708
782/782 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.8785 - loss: 0.0918
[0.09184686839580536, 0.8784800171852112]
782/782 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step


array([[0.22364613],
       [0.9853229 ],
       [0.68046236],
       ...,
       [0.11660443],
       [0.11622421],
       [0.36863568]], shape=(25000, 1), dtype=float32)