The gears of neural networks: Tensor operations

In [1]:
import numpy as np

In [ ]:
def naive_relu(x):
    assert len(x.shape) == 2
    x = x.copy()
    for i in range (x.shape[0]):
        for j in range (x.shape[1]):
            x[i,j] = max(x[i,j], 0)
    return x
    
x_with_negatives = np.array([[1.0, -0.5, 0.3, -2.0],
                             [-1.0, 0.8, -0.2, 1.5]])
print(x)
print(naive_relu(x))

[[ 1.  -0.5  0.3 -2. ]
 [-1.   0.8 -0.2  1.5]]
[[1.  0.  0.3 0. ]
 [0.  0.8 0.  1.5]]


In [14]:
def naive_add(x, y):
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i,j] += y[i,j]
            
    return x

x = np.random.rand(2,4)
y = np.random.rand(2,4)
print(x)
print(y)
print(naive_add(x,y))

[[0.44050845 0.54170616 0.83269626 0.71916955]
 [0.93487984 0.62050752 0.22467533 0.35820008]]
[[0.77371559 0.97920905 0.57944027 0.15634176]
 [0.08824781 0.23568626 0.34652213 0.24190138]]
[[1.21422404 1.52091521 1.41213653 0.87551131]
 [1.02312765 0.85619377 0.57119746 0.60010146]]


In [15]:
z = x + y
print(z)
print(np.maximum(z,0.))

[[1.21422404 1.52091521 1.41213653 0.87551131]
 [1.02312765 0.85619377 0.57119746 0.60010146]]
[[1.21422404 1.52091521 1.41213653 0.87551131]
 [1.02312765 0.85619377 0.57119746 0.60010146]]


In [17]:
def naive_add_matrix_and_vector(x,y):
    x=x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i,j] += y[j]
    return x
            
x = np.random.rand(2,3)
y = np.random.rand(3)

print(x)
print(y)
print(naive_add_matrix_and_vector(x,y))

[[0.73004279 0.71540376 0.78146939]
 [0.97935328 0.69748231 0.1894475 ]]
[0.59523354 0.83137319 0.28112924]
[[1.32527633 1.54677695 1.06259864]
 [1.57458682 1.5288555  0.47057674]]


In [18]:
def naive_vector_dot(x, y):
    z = 0
    for i in range(x.shape[0]):
        z += x[i] * y[i]
    return z

def naive_matrix_vector_dot(x, y):
    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        z[i] = naive_vector_dot(x[i,:], y)
        
    return z

print(naive_matrix_vector_dot(x,y))

[1.24900736 1.21607124]


RESHAPING

In [22]:
x = np.array([[0., 1.],
            [2., 3.],
            [4., 5.]])
print(x.shape)
x = x.reshape((6,1))
print(x)

(3, 2)
[[0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [5.]]


transposition

In [23]:
x = np.zeros((300,20))
x= np.transpose(x)
x.shape

(20, 300)